# Generated by Django 6.0.2 on 2026-02-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('it', 'Informatique'), ('rh', 'Ressources Humaines'), ('maintenance', 'Maintenance'), ('other', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumis'), ('IN_PROGRESS', 'En traitement'), ('COMPLETED', 'Completé'), ('CANCELLED', 'Rejeté')], max_length=30)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
