# Generated by Django 6.0.2 on 2026-02-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumis'), ('in_progess', 'En traitement'), ('completed', 'Completé'), ('canceled', 'Rejeté')], default='submitted', max_length=30),
        ),
    ]
