# Generated by Django 6.0.2 on 2026-02-16 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_alter_demande_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='demandeur',
        ),
        migrations.AddField(
            model_name='demande',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demande',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Soumise'), ('IN_PROGRESS', 'En traitement'), ('COMPLETED', 'Complétée'), ('CANCELED', 'Annulée')], default='SUBMITTED', max_length=30),
        ),
    ]
